import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  // Users table
  users: defineTable({
    name: v.string(),
    createdAt: v.number(),
  }),

  // Courses - stores user's learning sessions/history
  courses: defineTable({
    userId: v.id("users"),
    title: v.string(),
    originalPrompt: v.string(),
    pdfStorageId: v.optional(v.id("_storage")),
    lastPosition: v.number(), // Index of last watched video
    createdAt: v.number(),
  }).index("by_user", ["userId"]),

  // Feed Items - individual videos in a course
  feedItems: defineTable({
    courseId: v.id("courses"),
    videoId: v.string(), // YouTube video ID
    topicTitle: v.string(), // Generated by Gemini
    order: v.number(),
    metaData: v.object({
      channelName: v.string(),
      duration: v.optional(v.string()),
      thumbnailUrl: v.optional(v.string()),
      title: v.string(),
    }),
  }).index("by_course", ["courseId"]),
});
